export const BASE_API_URL = 'http://localhost:4000/api';
export const licenseKey =
  'eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NDA4NzM1OTksImp0aSI6IjQ3YmFlODVmLWVjNjgtNGJjZi05OWIxLTFhYWU5YWQ3OTBiYSIsInVzYWdlRW5kcG9pbnQiOiJodHRwczovL3Byb3h5LWV2ZW50LmNrZWRpdG9yLmNvbSIsImRpc3RyaWJ1dGlvbkNoYW5uZWwiOlsiY2xvdWQiLCJkcnVwYWwiLCJzaCJdLCJ3aGl0ZUxhYmVsIjp0cnVlLCJsaWNlbnNlVHlwZSI6InRyaWFsIiwiZmVhdHVyZXMiOlsiKiJdLCJ2YyI6ImIwYjg3NjY5In0.J6V0Vfgdi3ua2qBwVTLmqMWsIs2UzfHGveY0SRKrCukXMHzzTX8SvaGZl_HyOYG9fvwbEBVqg9gzTKs8nvlqxg';
